sudo: required
dist: xenial

language: python

python:
  - 3.5
  - 3.6
  - 3.7
  # - "nightly"
  # - "pypy3.5"

addons:
  apt:
    packages:
    - libmagic1
    - libjpeg-turbo8
    - libjpeg-turbo8-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g
    - zlib1g-dev
    - liblcms2-2
    - liblcms2-dev
    - liblcms2-utils
    - libtiff5-dev
    - libwebp-dev
  sonarcloud:
    organization: "jpstroop-github" # the key of the org you chose at step #3
    token:
      secure: "f4Uz9D81KoszIVu3yJXsvCDiVpgmq9YY6H1vM/Y30kH3mUkMMgc/Qny85+5753XLNZxv3+lhYETFmh7wT1/4r0eZ4jY4zzr31h0d+0E40/2t5ZyllAeehmBAj9I/oxWg59PqaiYOK9M//t7HNDy4qY7TG+SnQdMkMnrgnVOUqHXWRtEsfybOlknWPrYC2EYcI2nNIQMY83EUW3NYi8s4VYiHkGCj9s3uNu0kqPw8cBwnFrwsHNYIGDtXjdcVF/xRDh2LjyhXOlsUqRDgEmJZ8/fwYIEkdC+DXRVlsBQ1bBz+t7mWeP6zrKbz1KFHYrgnY/8JD9yAxOrCJmZCG36qfFSbdaCSA+LKJhQrytGPhto8Wii2HF8EoU6PU55gOBY4/r+9i806wgOPLUg43xsnmwV0nS2y97Z4tn8Kjo8UivlzLaMX4gZn9AGzNNUUmvvNzuei5PFEZz+7ZuBMGiYFJl/Y5BfGY6OZMc41OE9Q6PKIOjroKOsTQrMZNt0kuz4jJEzo/nNtLdlBJcjOMTDEk1zICkH3Kyf6lD4Rc+AC5uF0iFfybLCdvq0RyL3BIEYBAyVr0KbNWyvPamfyR51EBaP0d8KyaLq8URCIVcnBKcZbyCWnc+1Km0OUcEFHeUcNEB2aolo9YdAP94KYOkXCAhjDoPIrp4Z/M0TcifSzNBk="

install:
  - pipenv install --dev

# See https://pypi.python.org/pypi/pytest-cov
script:
  - py.test --cov=loris
  - sonar-scanner

after_success:
  coveralls

notifications:
  email:
    recipients: "jpstroop@gmail.com"
    on_success: "always"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
