sudo: required
dist: bionic

language: python

python:
  - 3.6
  - 3.7
  - 3.8

addons:
  apt:
    packages:
    - libmagic1
    - libjpeg-turbo8
    - libjpeg-turbo8-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g
    - zlib1g-dev
    - liblcms2-2
    - liblcms2-dev
    - liblcms2-utils
    - libtiff5-dev
    - libwebp-dev

install:
  - pipenv install --dev

# See https://pypi.python.org/pypi/pytest-cov
script: py.test -s --cov=loris

after_success:
  coveralls

notifications:
  email:
    recipients: "jpstroop@gmail.com"
    on_success: "always"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
